services:
  moodle:
    build:
      context: moodle
      args:
        SSL_CERTIFICATE_FILE: ...
        SSL_CERTIFICATE_KEY_FILE: ...
        SSL_CERTIFICATE_CHAIN_FILE: ...
    ports:
      - "5000:80"
      - "5443:443"
  anwesenheit:
    build: anwesenheit
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: db
      args:
        ANWESENHEIT_DB: anwesenheit
        ANWESENHEIT_USER: anwesenheit
        ANWESENHEIT_PASSWORD: anwesenheitpw
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: pgpassword
