version: "2.1"
services:
  moodle:
    build:
      context: moodle
      args:
        SSL_CERTIFICATE_FILE: ...
        SSL_CERTIFICATE_KEY_FILE: ...
        SSL_CERTIFICATE_CHAIN_FILE: ...
    ports:
      - "5000:80"
      - "5443:443"
    volumes:
    - ./moodle/moodle_data:/var/www/moodle_data
  anwesenheit:
    build: anwesenheit
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: db
      args:
        ANWESENHEIT_DB: anwesenheit
        ANWESENHEIT_USER: anwesenheit
        ANWESENHEIT_PASSWORD: anwesenheitpw
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: pgpassword
