#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $ANWESENHEIT_USER WITH PASSWORD '$ANWESENHEIT_PASSWORD';
	CREATE DATABASE $ANWESENHEIT_DB;
	GRANT ALL PRIVILEGES ON DATABASE $ANWESENHEIT_DB TO $ANWESENHEIT_USER;
	-- connect to moodle
	GRANT CONNECT ON DATABASE moodle TO $ANWESENHEIT_USER;
	GRANT USAGE ON SCHEMA public TO $ANWESENHEIT_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $ANWESENHEIT_USER;
EOSQL

